import type { Metadata } from "next";
import { PT_Sans } from "next/font/google"; // 1. Import PT_Sans
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

// 2. Initialize PT Sans with the weights from your link (400 and 700, normal and italic)
const ptSans = PT_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // 3. Attach the PT Sans variable to the HTML tag
      className={`${ptSans.variable} h-full antialiased`}
    >
      {/* 4. Use 'font-sans' so it applies globally to your body */}
      <body className="dark min-h-full flex flex-col font-sans">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
